dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: LL+/YOcridy5uU+ERFONQulQWYjyDy0pbGJtT7VC8OojJLWFmh4LlDNkX6mFo0cEaHPD88f70POXFEgHK8ibaKDnteh9udIHnK/FruwGWmf/Tddway1CoX3FWn1GCjwt5o+KvRQvsECwa4c30MXp/RTsqk3aOX2a21wnzPRFha9tcqNFOEBJY/itdvuqzD/V9fa3iZUbAtHLcyz6XcXALY8ISvMqVQit+OtlfoAbTXMLuWAkTltAF3rbMJ2ttSsHWJAOYlRZXNdBahNkN29NZZLgg/KBnTSPahB1NrL6Su+3jPT9ybpjAq44ow+7toWr4oghVkrxHQmwgetI9yTOWol+eqtmNhqbWTAE99bocFyArEnjnx9zGseJFtGGC9T7ymPLVUw5LXdzd1HqS/ZER9ml0no5St5+5N5TT9MhTHYBB3YRwYjTDOrBOhu4mCZwuTS4f46247R9JONbmEjLibsU76NJ36kc28WJ/awQC+0Vtk+XRHiGhTxFW/i+vRZBzN/KRCFoG5kSClITwJno1+Hfu8D1XJrBWpvfhXIkuDa6x59zMMjYa1G7cRF6pw07ig9QNmCBH09AXXSG6vkPAAEfvWQ801vf1e1quMNyO/pmAZqS9xYXH1na/E5nKh8hIXx8Bh7VRsJDwvJmhmqu0hUE+WqpAU3a/nBUw6C9cEw=
  file: Gerbers/PRO-112_gerbers.zip
  on:
    repo: w4xzr/PRO-112
  skip_cleanup: 'true'
